# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  nodeVersion: "16"
  cmakeVersion: "3.22.x"
  flutterVersion: "2.8.1"

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.nodeVersion }}
      - uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: ${{ env.cmakeVersion }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutterVersion }}
      - run: flutter config --enable-macos-desktop
      - run: flutter doctor -v
      - name: Npm install
        run: npm install --ignore-scripts
      - name: Build Cli Vendor App
        run: sh build_macos.sh
      - name: Upload Cli Vendor App
        run: OSS_AK=${{ secrets.ALIYUN_OSS_AK }} OSS_SK=${{ secrets.ALIYUN_OSS_SK }} node scripts/upload.js
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.nodeVersion }}
      - uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: ${{ env.cmakeVersion }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutterVersion }}
      - name: Install gtk
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter doctor -v
      - name: Npm install
        run: npm install --ignore-scripts
      - name: Build Cli Vendor App
        run: bash build_linux.sh
      - name: Upload Cli Vendor App
        run: OSS_AK=${{ secrets.ALIYUN_OSS_AK }} OSS_SK=${{ secrets.ALIYUN_OSS_SK }} node scripts/upload.js
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
